# Generated by Django 5.0.4 on 2024-04-19 13:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_siteweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(default='https://static.vecteezy.com/ti/vecteur-libre/p3/7296447-icone-utilisateur-dans-le-style-plat-icone-personne-symbole-client-vectoriel.jpg', upload_to='client_photos/'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='num_telephone',
            field=models.CharField(help_text='Le numéro de téléphone doit commencer par +212', max_length=15, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit commencer par +212', regex='^\\+212\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='num_tel',
            field=models.CharField(help_text='Le numéro de téléphone doit commencer par +212', max_length=15, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit commencer par +212', regex='^\\+212\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='promo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='image_places/'),
        ),
        migrations.AlterModelTable(
            name='activite',
            table='activite',
        ),
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='hotel',
            table='hotel',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurant',
        ),
        migrations.AlterModelTable(
            name='ville',
            table='ville',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_siteweb.client')),
            ],
            options={
                'db_table': 'like',
            },
        ),
        migrations.AddField(
            model_name='activite',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='activite_likes', to='app_siteweb.like'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='hotel_likes', to='app_siteweb.like'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='restaurant_likes', to='app_siteweb.like'),
        ),
        migrations.CreateModel(
            name='PlaceTouristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='places_touristiques/')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_touristiques', to='app_siteweb.ville')),
            ],
            options={
                'db_table': 'place_touristique',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_siteweb.client')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.AddField(
            model_name='activite',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='activite_reviews', to='app_siteweb.review'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='hotel_reviews', to='app_siteweb.review'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='restaurant_reviews', to='app_siteweb.review'),
        ),
    ]
