# Generated by Django 5.0.4 on 2024-04-29 20:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_siteweb', '0003_admin_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='num_tel',
        ),
        migrations.AddField(
            model_name='hotel',
            name='num_telephone',
            field=models.CharField(default='+212000000000', max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+212\\d{9}$')]),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_siteweb.client')),
            ],
            options={
                'db_table': 'rating',
            },
        ),
    ]
