# Generated by Django 5.0.4 on 2024-04-30 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_siteweb', '0007_hotel_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
