# Generated by Django 5.0.4 on 2024-04-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_siteweb', '0012_activite_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activite',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='activite',
            name='prix',
        ),
    ]
