# Generated by Django 5.0.4 on 2024-04-30 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_siteweb', '0013_remove_activite_likes_remove_activite_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='activite_likes', to='app_siteweb.like'),
        ),
        migrations.AlterField(
            model_name='activite',
            name='emplacement',
            field=models.CharField(default="pas d'emplacement fourni", max_length=255),
        ),
        migrations.AlterField(
            model_name='activite',
            name='num_telephone',
            field=models.CharField(default='+212000000000', help_text='Le numéro de téléphone doit commencer par +212', max_length=15, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit commencer par +212', regex='^\\+212\\d{9}$')]),
        ),
    ]
