# Generated by Django 5.0.4 on 2024-04-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_siteweb', '0014_activite_likes_alter_activite_emplacement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='slug',
            field=models.SlugField(default='Nom par défaut', max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(default='Nom par défaut', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default='Nom par défaut', max_length=255),
        ),
    ]
