# Generated by Django 5.0.4 on 2024-04-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_siteweb', '0015_activite_slug_hotel_slug_restaurant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
