# Generated by Django 5.0.4 on 2024-04-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_siteweb', '0016_alter_activite_slug_alter_hotel_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activite',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
