# Generated by Django 5.0.4 on 2024-05-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_siteweb', '0018_alter_client_managers_admin_groups_admin_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='client',
            name='prenom',
        ),
    ]
