# Generated by Django 5.0.4 on 2024-05-02 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_siteweb', '0020_alter_admin_is_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
